export const classes = {
  dashActiveBtn: "btn__dash-active",
  dashBtn: "btn__dash",
  dashPanel: "dashboard__panel",
  menu: "dashboard__menu",
  main: "dashboard__main",
  core: "dashboard",
  summary: {
    iconVideo: "summary__iconVideo",
    youtube: "summary__youtube",
    base: "summary__",
    correction: "summary__correction",
    correctionSpan: "summary__correction-span",
    error: "summary__error",
    errorSpan: "summary__error-span",
    card: "summary__card",
    title: "summary__title",
    channel: "summary__channel",
    container: "summary",
    read: "summary__read",
    status: "summary__status",
    arrow: "btn__arrow",
    info: "summary__card-info",
    form: "summary__form",
    btnSend: "summary__btnSend",
    processUpload: "summary__process-upload",
    scoreStats: "summary__score",
    scoreDetailsContainer: "summary__detail-scoreContainer",
    detailsBase: "summary__details",
    summaryError: "summary__errors",
    iconRead: "summary__iconRead",
    score: "summary__details-score",
    closeBtn: "summary__closeBtn",
    formTitle: "summary__form-title",
    newPanel: "summary__new-panel",
    readPanel: "summary__read-panel",
    iconContainer: "summary__iconsContainer",
    iconAlert: "summary__iconAlert",
    alertImg: "summary__iconAlert-img",
    list: "dashboard__summaries",
    textContainer: "summary__text-container",
    action: "summary__action",
    actionIconContainer: "summary__action-iconsContainer",
    errorTab: "summary__error-tab",
    errorBase: "summary__error-",
    errorOpen: "summary__error-open",
    errorClose: "summary__error-close",
    scoreContainer: "summary__score-container",
    errorsContainer: "summary__errors-container",
    processSpace: "summary__process-space",
    processLabel: "summary__process-label",
    processUnavailable: "summary__process-unavailable",
    processContainer: "summary__process-container",
    feed: "summary__feedback",
    score: {
      bad: "summary__iconScore-bad",
      medium: "summary__iconScore-medium",
      good: "summary__iconScore-good",
    },
  },
  lessons: {
    container: "dashboard__lessonsContainer",
    row: "dashboard__lessonRow",
    level: "dashboard__lessonLevel",
    error: "dashboard__lessonError",
    errorMsg: "dashboard__lessonError-msg",
    errorClose: "dashboard__lessonError-close",
    read: "dashboard__readLesson",
    unlock: "dashboard__lessonUnlock",
    title: "dashboard__lessonTitle",
    backToDashboard: "lesson__backToDashboard",
    mainLocked: "lesson__mainLocked",
    locked: "lesson__locked",
    textLocked: "lesson__lockedText",
    lockedBack: "lesson__lockedBack",
    singleCell: "lesson__cell-single",
    cellArray: "lesson__cell-array",
    cellBase: "lesson__cell",
    table: "lesson__table",
  },
  flashcards: {
    input: "flashcard__input",
    inputTrue: "flashcard__input-true",
    inputFalse: "flashcard__input-false",
    inputContainer: "flashcard__input-container",
    container: "flashcard__container",
    score: "flashcard__score",
    finish: "flashcards__finish",
    points: "flashcard__points",
    menu: "flashcard__menu",
    next: "flashcard__next",
    helpBtn: "flashcard__helpBtn",
    helpless: "flashcard__helpBtn-end",
    main: "flashcard__main",
    intro: "flashcard__intro",
    commands: "flashcard__command",
    start: "flashcard__start",
  },
  settings: {
    btnFetch: "settings__button-fetch",
    btnChange: "settings__button-change",
    btnClose: "settings__button-close",
    container: "settings__container",
    form: "settings__form",
    confirmTxt: "settings__confirmText",
    confirmBtn: "settings__confirmDeactivation",
    closeDeactivation: "settings__closeDeactivation",
    main: "settings__main",
    error: "settings__error",
    contractContainer: "settings__contractContainer",
    contractTitle: "settings__contractTitle",
    priceContainer: "settings__priceContainer",
    contractForm: "settings__contractForm",
    teacherMenu: "settings__teachersMenu",
    next: "settings__next",
    front: "settings__teacherFront",
    contractLabel: "settings__contractLabel",
    contractCost: "settings__contractCost",
    teacherList: "settings__teachersList",
    teacherProfile: "settings__teacherProfile",
    teacherData: "settings__teacherData",
    title: "settings__title",
    imgContainer: "settings__imgContainer",
    currencyInput: "settings__currency",
    emailInput: "settings__email",
    planInput: "settings__plan",
    labelPrice: "settings__labelPrice",
    breadcrumbContainer: "settings__breadcrumbContainer",
    breadcrumbBtn: "settings__breadcrumb-btn",
    breadcrumbActiveBtn: "settings__breadcrumb-activeBtn",
    breadcrumbText: "settings__breadcrumb-text",
    contractInput: "settings__contractInput",
    menu: "settings__menu",
    trash: "settings__delete",
    popUp: "settings__popUp",
    activate: "settings__activate-btn",
  },
  study: {
    menu: "dashboard__studyMenu",
    activeTab: "dashboard__studyMenu-tabActive",
    tab: "dashboard__studyMenu-tab",
  },
  error: "dashboard__error",
};

export const ids = {
  flashcardGuess: "flashcardGuess",
};

export const newSummaryInitialStep = {
  draft: null,
  correction: null,
  stats: null,
};

export const newSummaryInitialStatus = {
  draft: null,
  correction: null,
  stats: null,
};

export const statsSymbols = { up: "🢁", down: "🢃", equal: "≈" };

export const bars = ["draft", "correction", "stats"];

export const cardBaseURL =
  "https://hiyapbiaalaccnrtetxg.supabase.co/storage/v1/object/public/flashcards/";

export const userBaseURL =
  "https://hiyapbiaalaccnrtetxg.supabase.co/storage/v1/object/public/";

export const servicesMap = {
  subscription: {
    retriever: "contract.subscription",
    type: "number",
  },
  tutoring: {
    retriever: "contract.tutoring",
    type: "number",
  },
  speaking: {
    retriever: "contract.speaking",
    type: "number",
  },
  qNa: {
    retriever: "contract.qNa",
    type: "number",
  },
};
