import {
  userType,
  currentPrivacy,
  currentTos,
  langsArray,
  plans,
  dashboardStudentsTabs,
  dashboardTeachersTabs,
  supportedLangs,
  currencies,
  subscription,
  tutoring,
  speaking,
  qNa,
  currencyMap,
  passwordKeys,
  contracts,
  packs,
} from "./atomicConstants.js";

const constants = {
  currentPrivacy,
  currentTos,
  userType,
  langsArray,
  plans,
  dashboardStudentsTabs,
  dashboardTeachersTabs,
  supportedLangs,
  currencies,
  subscription,
  tutoring,
  speaking,
  qNa,
  currencyMap,
  passwordKeys,
  contracts,
  packs,
};

export default constants;
