export const API_URLS = {
  base: "http://localhost:4000/api",
  auth: {
    base: "/auth",
    login: "/login",
    logout: "/logout",
    signup: "/signup",
    check: "/check",
    isUnique: "/unique",
    verify: "/verify/",
    forgotten: "/forgotten",
    newPsw: "/newPassword/",
    retrieve: "/retrieve",
  },
  dashboard: {
    base: "/dashboard",
    summaries: "/summariesList",
    summary: "/newSummary",
    correction: "/aiCorrection",
    stats: "/newStat",
    allStats: "/getStats",
    flashcards: "/flashcards",
    teachers: "/teachers",
  },
  messages: {
    base: "/messages",
    new: "/new",
  },
  trackers: {
    base: "/trackers",
    lessons: "/unlockedLessons",
    unlock: "/unlockLesson",
  },
  update: {
    base: "/update",
    profilePic: "/profilePic",
    settings: "/settings",
    password: "/newPassword",
  },
};
