export const classes = {
  dashActiveBtn: "btn__dash-active",
  dashBtn: "btn__dash",
  dashPanel: "dashboard__panel",
  summary: {
    base: "summary__",
    correction: "summary__correction",
    error: "summary__error",
    errorSpan: "summary__error-span",
    card: "summary__card",
    title: "summary__title",
    channel: "summary__channel",
    container: "summary",
    read: "summary__read",
    status: "summary__status",
    arrow: "btn__arrow",
    info: "summary__card-info",
    form: "summary__form",
    btnSend: "summary__btnSend",
    processUpload: "summary__process-upload",
    score: "summary__detalis-score",
    closeBtn: "summary__closeBtn",
    formTitle: "summary__form-title",
    newPanel: "summary__new-panel",
    readPanel: "summary__read-panel",
    iconContainer: "summary__iconsContainer",
    iconAlert: "summary__iconAlert",
    alertImg: "summary__iconAlert-img",
    list: "dashboard__summaries",
    textContainer: "summary__text-container",
    action: "summary__action",
    actionIconContainer: "summary__action-iconsContainer",
    errorTab: "summary__error-tab",
    errorBase: "summary__error-",
    errorOpen: "summary__error-open",
    errorClose: "summary__error-close",
    score: {
      bad: "summary__iconScore-bad",
      medium: "summary__iconScore-medium",
      good: "summary__iconScore-good",
    },
  },
};

export const newSummaryInitialState = {
  draft: null,
  correction: null,
  stats: null,
};

export const bars = ["draft", "correction", "stats"];
